metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"

db_engine = "sqlite"

replication_factor = 1

compression_level = 1

rpc_bind_addr = "[::]:3900"
rpc_public_addr = "127.0.0.1:3900"
rpc_secret = "1799bccfd7411eddcf9ebd316bc1f5287ad12a68094e1c6ac6abde7e6feae1ec"

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3902"
root_domain = ".s3.garage.localhost"

[s3_web]
bind_addr = "[::]:3903"
root_domain = ".web.garage.localhost"
index = "index.html"

[admin]
api_bind_addr = "[::]:3901"
admin_token = "changeme1234"
metrics_token = "changeme1234"
